In [1]:
import scipy.io as spio
import numpy as np

In [2]:
ls ../data/

bci/                        bike_data/           sentiments/
bci_EEG_data/               financial_data/      smartwatch_data/
bci_EEG_data-new/           har-data/            text_data/
bci-project-data-FILTERED/  hr_data/             translation_data/
bci-project-data-RAW/       kaggle-music-genre/
bci-sample-data/            MNIST_data/


In [3]:
executive = spio.loadmat(file_name='../data/bci_EEG_data/executive.mat')

In [4]:
executive.keys(), executive['executive'].shape

(dict_keys(['__header__', '__version__', '__globals__', 'executive']),
 (4239384, 13))

In [5]:
executive_label = spio.loadmat(file_name='../data/bci_EEG_data/executive_label.mat')

In [6]:
executive_label.keys()

dict_keys(['__header__', '__version__', '__globals__', 'label'])

In [7]:
executive_label['label'].shape

(4239384, 1)

In [8]:
executive_label_all = executive_label['label']

In [9]:
executive_label_all.shape, executive_label_all.dtype, (executive_label_all.max(axis=0) + 1)

((4239384, 1), dtype('<u2'), array([4], dtype=uint16))

In [10]:
imagery = spio.loadmat(file_name='../data/bci_EEG_data/imagery.mat')

In [11]:
imagery.keys()

dict_keys(['__header__', '__version__', '__globals__', 'imagery'])

In [12]:
imagery['imagery'].shape

(4239376, 13)

In [13]:
imagery_label = spio.loadmat(file_name='../data/bci_EEG_data/imagery_label.mat')

In [14]:
imagery_label.keys()

dict_keys(['__header__', '__version__', '__globals__', 'label'])

In [15]:
imagery_label['label'].shape

(4239376, 1)

In [16]:
imagery_label_all = imagery_label['label']

In [17]:
imagery_label_all.max(axis=0) + 1

array([4], dtype=uint16)

In [18]:
new_executive = spio.loadmat(file_name='../data/bci_EEG_data-new/new_executive.mat')

In [19]:
new_executive.keys()

dict_keys(['__header__', '__version__', '__globals__', 'new_executive'])

In [20]:
new_executive_data = new_executive['new_executive']

In [21]:
new_executive_data.shape, new_executive_data.dtype

((3072, 13, 1380), dtype('<f8'))

In [22]:
new_executive_data_transposed = new_executive_data.transpose(2, 0, 1)
new_executive_data_transposed.shape

(1380, 3072, 13)

In [23]:
new_executive_label = spio.loadmat(file_name='../data/bci_EEG_data-new/new_executive_label.mat')

In [24]:
new_executive_label.keys()

dict_keys(['__header__', '__version__', '__globals__', 'new_executive_label'])

In [25]:
new_executive_label_all = new_executive_label['new_executive_label']

In [27]:
new_executive_label_all.shape

(1380, 1)

In [28]:
new_executive_label_all.max(axis=0)+1

array([4], dtype=uint16)

In [29]:
new_imagery = spio.loadmat(file_name='../data/bci_EEG_data-new/new_imagery.mat')

In [30]:
new_imagery.keys()

dict_keys(['__header__', '__version__', '__globals__', 'new_imagery'])

In [31]:
new_imagery_data = new_imagery['new_imagery']

In [32]:
new_imagery_data.shape, new_imagery_data.dtype

((3584, 13, 1380), dtype('<f8'))

In [33]:
new_imagery_data_transposed = new_imagery_data.transpose(2, 0, 1)
new_imagery_data_transposed.shape

(1380, 3584, 13)

In [34]:
new_imagery_label = spio.loadmat(file_name='../data/bci_EEG_data-new/new_imagery_label.mat')

In [35]:
new_imagery_label.keys()

dict_keys(['__header__', '__version__', '__globals__', 'new_imagery_label'])

In [36]:
new_imagery_label_all = new_imagery_label['new_imagery_label']

In [37]:
new_imagery_label_all.shape, new_imagery_label_all.dtype

((1380, 1), dtype('<u2'))

In [38]:
new_imagery_label_all.max(axis=0)+1

array([4], dtype=uint16)

In [39]:
(np.mean(new_imagery_label_all==0), np.mean(new_imagery_label_all==1), 
 np.mean(new_imagery_label_all==2), np.mean(new_imagery_label_all==3),
np.mean(new_imagery_label_all==4), np.mean(new_imagery_label_all==5))

(0.0, 0.33333333333333331, 0.33333333333333331, 0.33333333333333331, 0.0, 0.0)

In [40]:
new_imagery_label_all.max()

3

In [41]:
(np.mean(new_executive_label_all==0), np.mean(new_executive_label_all==1), 
 np.mean(new_executive_label_all==2), np.mean(new_executive_label_all==3),
np.mean(new_executive_label_all==4), np.mean(new_executive_label_all==5))

(0.0, 0.33333333333333331, 0.33333333333333331, 0.33333333333333331, 0.0, 0.0)