In [1]:
import scipy.io as spio
import numpy as np

In [3]:
ls ../data/

bci/                         bci-sample-data/     sentiments/
bci_EEG_data/                bike_data/           smartwatch_data/
bci_EEG_data-dl_proj/        financial_data/      text_data/
bci_EEG_data-dl_proj-final/  har-data/            translation_data/
bci_EEG_data-new/            hr_data/             uci_ml_eeg/
bci-project-data-FILTERED/   kaggle-music-genre/
bci-project-data-RAW/        MNIST_data/


In [3]:
BahramFace = spio.loadmat(file_name='../data/bci-project-data-RAW/BahramFace.mat')
DJFace = spio.loadmat(file_name='../data/bci-project-data-RAW/DJFace.mat')
NickFace = spio.loadmat(file_name='../data/bci-project-data-RAW/NickFace.mat')
RoohiFace = spio.loadmat(file_name='../data/bci-project-data-RAW/RoohiFace.mat')
SarahFace = spio.loadmat(file_name='../data/bci-project-data-RAW/SarahFace.mat')

In [4]:
BahramFace.keys(), DJFace.keys(), NickFace.keys(), RoohiFace.keys(), SarahFace.keys()

(dict_keys(['__header__', '__version__', '__globals__', 'Intensification_Data', 'Intensification_Label']),
 dict_keys(['__header__', '__version__', '__globals__', 'Intensification_Data', 'Intensification_Label']),
 dict_keys(['__header__', '__version__', '__globals__', 'Intensification_Data', 'Intensification_Label']),
 dict_keys(['__header__', '__version__', '__globals__', 'Intensification_Data', 'Intensification_Label']),
 dict_keys(['__header__', '__version__', '__globals__', 'Intensification_Data', 'Intensification_Label']))

In [5]:
(BahramFace['Intensification_Data'].shape, DJFace['Intensification_Data'].shape, 
NickFace['Intensification_Data'].shape, RoohiFace['Intensification_Data'].shape,
SarahFace['Intensification_Data'].shape)

((3600, 205, 16),
 (3780, 205, 16),
 (3780, 205, 16),
 (3780, 205, 16),
 (3780, 205, 16))

In [6]:
length = int(BahramFace['Intensification_Data'].shape[0] * 0.30)

In [7]:
# Train and test: 0.7 vs 0.3
BahramFace['Intensification_Data'][:-length].shape, BahramFace['Intensification_Data'][-length:].shape

((2520, 205, 16), (1080, 205, 16))

In [8]:
FacesDataTrain = np.vstack(tup=(BahramFace['Intensification_Data'][:-length], 
                       DJFace['Intensification_Data'][:-length], 
                       NickFace['Intensification_Data'][:-length],
                      RoohiFace['Intensification_Data'][:-length],
                      SarahFace['Intensification_Data'][:-length]))

In [9]:
FacesDataTrain.shape, FacesDataTrain.dtype

((13320, 205, 16), dtype('<f8'))

In [10]:
FacesDataValid = np.vstack(tup=(BahramFace['Intensification_Data'][-length:], 
                       DJFace['Intensification_Data'][-length:], 
                       NickFace['Intensification_Data'][-length:],
                      RoohiFace['Intensification_Data'][-length:],
                      SarahFace['Intensification_Data'][-length:]))

In [11]:
FacesDataValid.shape, FacesDataValid.dtype

((5400, 205, 16), dtype('<f8'))

In [12]:
FacesLabelTrain = np.vstack(tup=(BahramFace['Intensification_Label'][:-length], 
                       DJFace['Intensification_Label'][:-length], 
                       NickFace['Intensification_Label'][:-length],
                      RoohiFace['Intensification_Label'][:-length],
                      SarahFace['Intensification_Label'][:-length]))

In [13]:
FacesLabelTrain.shape, FacesLabelTrain.dtype

((13320, 1), dtype('uint8'))

In [14]:
FacesLabelValid = np.vstack(tup=(BahramFace['Intensification_Label'][-length:], 
                       DJFace['Intensification_Label'][-length:], 
                       NickFace['Intensification_Label'][-length:],
                      RoohiFace['Intensification_Label'][-length:],
                      SarahFace['Intensification_Label'][-length:]))

In [15]:
FacesLabelValid.shape, FacesLabelValid.dtype

((5400, 1), dtype('uint8'))

In [16]:
FacesLabelAll = np.vstack(tup=(BahramFace['Intensification_Label'][:], 
                       DJFace['Intensification_Label'][:], 
                       NickFace['Intensification_Label'][:],
                      RoohiFace['Intensification_Label'][:],
                      SarahFace['Intensification_Label'][:]))

In [17]:
(FacesLabelAll.shape, FacesLabelTrain.shape, FacesLabelValid.shape, 
FacesLabelAll.dtype, FacesLabelTrain.dtype, FacesLabelValid.dtype)

((18720, 1),
 (13320, 1),
 (5400, 1),
 dtype('uint8'),
 dtype('uint8'),
 dtype('uint8'))

In [18]:
(FacesLabelAll==0).shape, FacesLabelAll.shape

((18720, 1), (18720, 1))

In [19]:
np.mean(FacesLabelAll==0)

0.83333333333333337

In [20]:
(np.mean(BahramFace['Intensification_Label']==0), np.mean(DJFace['Intensification_Label']==0),
np.mean(NickFace['Intensification_Label']==0), np.mean(RoohiFace['Intensification_Label']==0), 
np.mean(SarahFace['Intensification_Label']==0))

(0.83333333333333337,
 0.83333333333333337,
 0.83333333333333337,
 0.83333333333333337,
 0.83333333333333337)

In [21]:
BahramFlipp = spio.loadmat(file_name='../data/bci-project-data-RAW/BahramFlipp.mat')
DJFlipp = spio.loadmat(file_name='../data/bci-project-data-RAW/DJFlipp.mat')
NickFlipp = spio.loadmat(file_name='../data/bci-project-data-RAW/NickFlipp.mat')
RoohiFlipp = spio.loadmat(file_name='../data/bci-project-data-RAW/RoohiFlipp.mat')
SarahFlipp = spio.loadmat(file_name='../data/bci-project-data-RAW/SarahFlipp.mat')

In [22]:
(np.mean(BahramFlipp['Intensification_Label']==0), np.mean(DJFlipp['Intensification_Label']==0),
np.mean(NickFlipp['Intensification_Label']==0), np.mean(RoohiFlipp['Intensification_Label']==0), 
np.mean(SarahFlipp['Intensification_Label']==0))

(0.83333333333333337,
 0.83333333333333337,
 0.83333333333333337,
 0.83333333333333337,
 0.83333333333333337)

In [23]:
y = spio.loadmat(file_name='../data/bci-sample-data/y.mat')

In [24]:
LabelsAll = y['Intensification_SType']

In [25]:
LabelsAll.shape, LabelsAll.dtype

((6480, 192), dtype('uint8'))

In [30]:
np.mean(LabelsAll == 0)

0.83333333333333337

In [31]:
executive = spio.loadmat(file_name='../data/bci_EEG_data/executive.mat')

In [34]:
executive.keys(), executive['executive'].shape

(dict_keys(['__header__', '__version__', '__globals__', 'executive']),
 (4239384, 13))

In [35]:
executive_label = spio.loadmat(file_name='../data/bci_EEG_data/executive_label.mat')

In [36]:
executive_label.keys()

dict_keys(['__header__', '__version__', '__globals__', 'label'])

In [39]:
executive_label['label'].shape

(4239384, 1)

In [40]:
executive_label_all = executive_label['label']

In [44]:
executive_label_all.shape, executive_label_all.dtype, (executive_label_all.max(axis=0) + 1)

((4239384, 1), dtype('<u2'), array([4], dtype=uint16))

In [46]:
imagery = spio.loadmat(file_name='../data/bci_EEG_data/imagery.mat')

In [47]:
imagery.keys()

dict_keys(['__header__', '__version__', '__globals__', 'imagery'])

In [48]:
imagery['imagery'].shape

(4239376, 13)

In [49]:
imagery_label = spio.loadmat(file_name='../data/bci_EEG_data/imagery_label.mat')

In [50]:
imagery_label.keys()

dict_keys(['__header__', '__version__', '__globals__', 'label'])

In [51]:
imagery_label['label'].shape

(4239376, 1)

In [52]:
imagery_label_all = imagery_label['label']

In [53]:
imagery_label_all.max(axis=0) + 1

array([4], dtype=uint16)

In [54]:
new_executive = spio.loadmat(file_name='../data/bci_EEG_data-new/new_executive.mat')

In [55]:
new_executive.keys()

dict_keys(['__header__', '__version__', '__globals__', 'new_executive'])

In [56]:
new_executive_data = new_executive['new_executive']

In [57]:
new_executive_data.shape, new_executive_data.dtype

((3072, 13, 1380), dtype('<f8'))

In [72]:
new_executive_data_transposed = new_executive_data.transpose(2, 0, 1)
new_executive_data_transposed.shape

(1380, 3072, 13)

In [15]:
new_executive_label = spio.loadmat(file_name='../data/bci_EEG_data-new/new_executive_label.mat')

In [16]:
new_executive_label.keys()

dict_keys(['__header__', '__version__', '__globals__', 'new_executive_label'])

In [17]:
new_executive_label_all = new_executive_label['new_executive_label']

In [66]:
new_executive_label_all.shape, new_imagery_label_all.dtype

((1380, 1), dtype('<u2'))

In [67]:
new_executive_label_all.max(axis=0)+1

array([4], dtype=uint16)

In [68]:
new_imagery = spio.loadmat(file_name='../data/bci_EEG_data-new/new_imagery.mat')

In [69]:
new_imagery.keys()

dict_keys(['__header__', '__version__', '__globals__', 'new_imagery'])

In [70]:
new_imagery_data = new_imagery['new_imagery']

In [71]:
new_imagery_data.shape, new_imagery_data.dtype

((3584, 13, 1380), dtype('<f8'))

In [73]:
new_imagery_data_transposed = new_imagery_data.transpose(2, 0, 1)
new_imagery_data_transposed.shape

(1380, 3584, 13)

In [3]:
new_imagery_label = spio.loadmat(file_name='../data/bci_EEG_data-new/new_imagery_label.mat')

In [4]:
new_imagery_label.keys()

dict_keys(['__header__', '__version__', '__globals__', 'new_imagery_label'])

In [5]:
new_imagery_label_all = new_imagery_label['new_imagery_label']

In [6]:
new_imagery_label_all.shape, new_imagery_label_all.dtype

((1380, 1), dtype('<u2'))

In [7]:
new_imagery_label_all.max(axis=0)+1

array([4], dtype=uint16)

In [14]:
(np.mean(new_imagery_label_all==0), np.mean(new_imagery_label_all==1), 
 np.mean(new_imagery_label_all==2), np.mean(new_imagery_label_all==3),
np.mean(new_imagery_label_all==4), np.mean(new_imagery_label_all==5))

(0.0, 0.33333333333333331, 0.33333333333333331, 0.33333333333333331, 0.0, 0.0)

In [13]:
new_imagery_label_all.max()

3

In [18]:
(np.mean(new_executive_label_all==0), np.mean(new_executive_label_all==1), 
 np.mean(new_executive_label_all==2), np.mean(new_executive_label_all==3),
np.mean(new_executive_label_all==4), np.mean(new_executive_label_all==5))

(0.0, 0.33333333333333331, 0.33333333333333331, 0.33333333333333331, 0.0, 0.0)