# fNIRS data for Human Activity Recognition (HAR)

In [1]:
import numpy as np
import os
import pandas as pd

In [30]:
% ls ../../../datasets/fNIRs_data/P11-4-17-2018/
# % find ../../datasets/fNIRs_data/ | grep fNIR_data

ls: cannot access '../../../datasets/fNIRs_data/P11-4-17-2018/': No such file or directory


In [31]:
% ls ../../../datasets/fNIRs_data/

P12-4-17-2018/  P14-4-18-2018/  P16-4-18-2018/
P13-4-17-2018/  P15-4-18-2018/  P17-4-18-2018/


In [32]:
def find_all(name, path):
    result = []
    for root, dirs, files in os.walk(path):
        if name in files:
            result.append(os.path.join(root, name))
    return result

In [33]:
allpaths = find_all(name='fNIR_data.txt', path='/home/arasdar/datasets/fNIRs_data/')

In [39]:
# 7 folders and subjects
# 5 folders 
# 7*5=35 but there are 34 so one is missing.
# This is why I got rid of the first which was subject P11.
# 6 subjects and 5 activities = 30 files
# 1, 2, 3, 4, 5
# 0, 1, 2, 3, 4 these are all the classes
((sorted(allpaths, reverse=False)), len(allpaths))

(['/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/1. Right Hand/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/2. Both Hands/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/3. Left Hand/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/4. Right Leg/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/5. Left Leg/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P13-4-17-2018/1. Right Hand/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P13-4-17-2018/2. Both Hands/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P13-4-17-2018/3. Left Hand/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P13-4-17-2018/4. Right Leg/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P13-4-17-2018/5. Left Leg/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P14-4-18-2018/1. Right Hand/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data/P14-4-18-2018/2. Both Hands/fNIR_data.txt',
  '/home/arasdar/datasets/fNIRs_data

In [41]:
allpaths[0], allpaths[-1], allpaths[23]

('/home/arasdar/datasets/fNIRs_data/P16-4-18-2018/4. Right Leg/fNIR_data.txt',
 '/home/arasdar/datasets/fNIRs_data/P17-4-18-2018/5. Left Leg/fNIR_data.txt',
 '/home/arasdar/datasets/fNIRs_data/P14-4-18-2018/3. Left Hand/fNIR_data.txt')

In [49]:
# df: data frame object
df = []
for each_idx in range(len(allpaths)):
    df.append(pd.read_csv(filepath_or_buffer=allpaths[each_idx], names=['time', 'sample', 
                       'channel', 'channel', 'channel', 'channel', 'channel',
                       'channel', 'channel', 'channel', 'channel', 'channel',
                       'channel', 'channel', 'channel', 'channel', 'channel',
                       'channel', 'channel', 'channel', 'channel', 'channel',
                       'channel', 'channel', 'channel', 'channel', 'channel',
                       'channel', 'channel', 'channel', 'channel', 'channel',
                       'channel', 'channel', 'channel', 'channel', 'channel',
                       'channel', 'channel', 'channel', 'channel', 'channel']))

/home/arasdar/anaconda3/envs/arasdar-DL-env/lib/python3.6/site-packages/pandas/io/parsers.py:709: UserWarning: Duplicate names specified. This will raise an error in the future.
  return _read(filepath_or_buffer, kwds)


In [56]:
# len(df), df[0].shape, df[0].head()

In [57]:
for each in range(len(df)):
#     print(df[each]['sample'][2])
    df[each]['sample'][1:] = df[each]['sample'][1:].astype(str).str[2:]
    df[each]['channel.39'][1:] = df[each]['channel.39'][1:].astype(str).str[1:-1]    
# # df[23], allpaths[23], 
# #  '/home/arasdar/datasets/fNIRs_data/P11-4-17-2018/Right Leg/fNIR_data.txt')
# pd.read_csv(filepath_or_buffer=allpaths[23], names=['time', 'sample', 
#                        'channel', 'channel', 'channel', 'channel', 'channel',
#                        'channel', 'channel', 'channel', 'channel', 'channel',
#                        'channel', 'channel', 'channel', 'channel', 'channel',
#                        'channel', 'channel', 'channel', 'channel', 'channel',
#                        'channel', 'channel', 'channel', 'channel', 'channel',
#                        'channel', 'channel', 'channel', 'channel', 'channel',
#                        'channel', 'channel', 'channel', 'channel', 'channel',
#                        'channel', 'channel', 'channel', 'channel', 'channel']).head(), allpaths[23]

/home/arasdar/anaconda3/envs/arasdar-DL-env/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
/home/arasdar/anaconda3/envs/arasdar-DL-env/lib/python3.6/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.


In [58]:
# for each in range(len(df)):
#     print(df[each].head())
# # df['sample']

In [59]:
matrices = []
for each in range(len(df)):
    matrices.append(df[each][1:].as_matrix().astype(float))

In [201]:
# # For every single data or txt file here we have a label
# # In total we 'll have five labels: 1, 2, 3, 4, 5
# # These labels converted to a number will be: 0, 1, 2, 3, 4
# # this would be 5 dimensional array
# # starting like this:
# np.array([1, 0, 0, 0, 0])
# np.array([0, 1, 0, 0, 0])
# # 0 1 0 0 0 
# # 0 0 1 0 0
# # 0 0 0 1 0
# # 0 0 0 0 1
# # ----------server/datasets/Project-HAR/subject-date/activity-class/input-data
# # (['/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/1. Right Hand/fNIR_data.txt',
# #   '/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/2. Both Hands/fNIR_data.txt',
# #   '/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/3. Left Hand/fNIR_data.txt',
# #   '/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/4. Right Leg/fNIR_data.txt',
# #   '/home/arasdar/datasets/fNIRs_data/P12-4-17-2018/5. Left Leg/fNIR_data.txt',
# # len(data)
# # For every single row in the matrix, 
# # there is gonna be a correspondence/ label/ supervision.
# # That s how we can label this fNIRs signal.
# # This is very much like the txt file and the folder
# # it is subject independent, gender independent.
# # fNIRs data meaning data dependent
# # labeled/ certain activity
# # subject and date independent

In [188]:
data, labels = [], []
for row in range(0, len(matrices), 1):
    data.append(matrices[row][:, 2:])
    mat = np.zeros([data[row].shape[0], 5])
    # for each in range(mat.shape[0]):
    mat[:, row%5] = 1
    labels.append(mat)
#     print('mat, len(labels): ', mat, len(labels))

In [196]:
data[0].shape, labels[0].shape
data[0][1], labels[0][1]

(array([0.25568253, 0.13550095, 0.22802679, 0.48467571, 0.23755921,
        0.16856721, 0.29574981, 0.7120409 , 0.83408046, 0.24134316,
        0.4348596 , 0.10550072, 0.12523653, 0.29109681, 0.22010829,
        0.16065139, 0.39467266, 0.59167653, 0.17369114, 0.5237844 ,
        0.3942053 , 0.26517305, 0.32810646, 0.93380678, 0.4306449 ,
        0.23833884, 0.52017915, 1.09951508, 1.2449733 , 0.3827343 ,
        0.4514387 , 0.22096752, 0.22596563, 0.50641578, 0.34252322,
        0.21044534, 0.52494335, 0.75623262, 0.2755928 , 0.778355  ]),
 array([1., 0., 0., 0., 0.]))

In [199]:
# ToDO
# Standardizing the dataset or normalizing the dataset
# The question here is: if we should normalize/standardize every single batch alone or
# normalize them all together?
# X = np.array(data)
# X.shape, X.dtype
# X = np.zeros_like(data[0])
# X.shape, X.dtype
X, Y = data[0], labels[0] # initialize the stack
X.shape, X.dtype, Y.shape, Y.dtype
for each in range(1, len(data), 1): # start, stop, step
    X = np.vstack(tup=(X, data[each]))
    Y = np.vstack(tup=(Y, labels[each]))

In [200]:
X.shape, X.dtype, X[300, 10], data[0][300, 10],
Y.shape, Y.dtype, Y[300, 2], labels[0][300, 2],
# t, n = 8387+1195+2383 -1, 40-1
# X[t, n], data[3-1][2383 -1][n]

((50405, 5), dtype('float64'), 0.0, 0.0)

In [15]:
Xnorm = (X - X.mean(axis=0))/ X.std(axis=0)
Xnorm.shape, Xnorm.dtype, Xnorm.mean(axis=0), Xnorm.std(axis=0)

((133168, 40),
 dtype('float64'),
 array([ 3.24409756e-17, -1.56228909e-16, -1.70741977e-17,  1.70741977e-17,
        -8.19561488e-17,  1.05860026e-16,  6.82967907e-17, -7.51264697e-17,
        -5.80522721e-17, -5.20763029e-17,  8.19561488e-17,  2.73187163e-17,
        -1.53667779e-17,  8.70784081e-17, -1.62204878e-16, -1.66473427e-16,
        -8.53709883e-17, -1.17811964e-16,  5.80522721e-17, -1.09274865e-16,
         1.51960359e-16, -2.11293196e-17, -3.04134146e-17,  6.82967907e-18,
         1.22934223e-16,  1.28056482e-17, -2.39038767e-17, -5.46374325e-17,
         4.69540436e-17, -3.58558151e-17, -7.85413093e-17, -3.41483953e-17,
         4.95151732e-17,  6.14671116e-17, -2.73187163e-17, -2.04890372e-17,
         9.90303464e-17, -2.56112965e-17,  7.25653401e-17,  8.87858278e-17]),
 array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1.]))

In [16]:
sr = 0.129 # 111933.573-111933.504 is the difference between each two samples or sampling rate
each_trial=30 # 30seconds=20sec+10sec
# num_samples_per_trial
# each trial or epoch based on BCI course
# height or window size
30/0.129, np.floor(30/0.129), np.ceil(30/0.129)
# The size of each image for convnet will be 233x40x1 which is equal to the format NHWC, txn or NWC
# NWC is for signals since all the channels are projected the same as all channels in an image as well.
# In each convolutionn for image or signals the channels are all included for filtering
# Image or video might be part of this
# Image is NHWC or NCHW
# Signal is NWC or NCW
# N is the number of trials/epochs/windows
# C is the number of channels is 40 in this experiment: 20 for hemoglobin with o2 and 20 for hemoglobin with co2
# W is the window width size or signal window size which is 233
width = np.ceil(30/0.129)
# This is the number of minibatches per file
num_mb = mat.shape[0] - width +1
# num_mb # number of minibatches
# totla number of all the windows with the overlapping windows of 1 sample
num_mb, width
# len(allpaths), allpaths[44], num_mb*len(allpaths)

(485.0, 233.0)

In [17]:
width, l, h, Xnt, Xnv = 250, 0, 0, [], []
for idx in range(0, len(data), 1): # start, stop, step
    l = h
    h += data[idx].shape[0]
    #     print(idx, l, h, h-width, Xnorm.shape, data[idx].shape, Xnorm[l:h].shape, width)
    Xnt.append(Xnorm[l:h-width])
    Xnv.append(Xnorm[h-width:h])
    print(Xnt[idx].shape, Xnv[idx].shape, data[idx].shape, width)    
    print(Xnt[idx].dtype, Xnv[idx].dtype, data[idx].dtype, width)

(8137, 40) (250, 40) (8387, 40) 250
float64 float64 float64 250
(945, 40) (250, 40) (1195, 40) 250
float64 float64 float64 250
(2133, 40) (250, 40) (2383, 40) 250
float64 float64 float64 250
(979, 40) (250, 40) (1229, 40) 250
float64 float64 float64 250
(2124, 40) (250, 40) (2374, 40) 250
float64 float64 float64 250
(946, 40) (250, 40) (1196, 40) 250
float64 float64 float64 250
(952, 40) (250, 40) (1202, 40) 250
float64 float64 float64 250
(2154, 40) (250, 40) (2404, 40) 250
float64 float64 float64 250
(945, 40) (250, 40) (1195, 40) 250
float64 float64 float64 250
(2129, 40) (250, 40) (2379, 40) 250
float64 float64 float64 250
(991, 40) (250, 40) (1241, 40) 250
float64 float64 float64 250
(979, 40) (250, 40) (1229, 40) 250
float64 float64 float64 250
(2136, 40) (250, 40) (2386, 40) 250
float64 float64 float64 250
(973, 40) (250, 40) (1223, 40) 250
float64 float64 float64 250
(2128, 40) (250, 40) (2378, 40) 250
float64 float64 float64 250
(976, 40) (250, 40) (1226, 40) 250
float64 float

In [18]:
# This is scanning through the signal and extracting the minibatches
# TO be accurate and having more samples, I want to scan it with the 
# window size=250, overlap/stride=1, no padding
# Xnt-minibatches, only test one of them
Xnt[0].shape, width, Xnt[0].shape[0]-width+1, Xnt[1].shape[0]-width+1
# total number of minibatches extracted from each sample
num_mb = 0
for each in range(len(Xnt)):
#     print(Xnt[each].shape[0]-width+1)
    num_mb += Xnt[each].shape[0]-width+1
print(num_mb)    

111212


In [19]:
# Let's try to extract batches/minibatches from the first set of training data
# The number of minibatches are equal to
# This is the number of minibatches in the first set
num_mb = Xnt[0].shape[0]-width+1
# this the python list for holding all the minibatches inside
mb=[]
for each in range(num_mb):
    #it has to start from 0+step:width+step/stride and sweeping the entire signal
#     for stride in range()
# The number of minibatches should be equal to the length of the list
    mb.append(Xnt[0][each:each+width, :])

In [20]:
# Let s double check the minibatches list length and the estimated number of minibatches
len(mb), num_mb, mb[0].shape

(7888, 7888, (250, 40))

In [21]:
num_mb = Xnt[1].shape[0]-width+1
for each in range(num_mb):
    mb.append(Xnt[1][each:each+width, :])

In [22]:
num_mb, len(mb), 7888+696

(696, 8584, 8584)

In [23]:
num_mb = Xnt[2].shape[0]-width+1
for each in range(num_mb):
    mb.append(Xnt[2][each:each+width, :])

In [24]:
num_mb, len(mb), 7888+696+1884

(1884, 10468, 10468)

In [25]:
mb = []
for eachXnt in range(len(Xnt)):
    num_mb = Xnt[eachXnt].shape[0]-width+1
    for each in range(num_mb):
        mb.append(Xnt[eachXnt][each:each+width, :])

In [26]:
# # len(mb)
# for each in Xnt:
#     print(each.shape, each.dtype)
len(Xnt), len(mb), len(Xnv)

(44, 111212, 44)

In [27]:
# len(mb)
for each in Xnv:
    print(each.shape, each.dtype)

(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
(250, 40) float64
